Systex: Markdown writer introduced

diff --git a/.diva/cmd/check b/.diva/cmd/check
--- a/.diva/cmd/check
+++ b/.diva/cmd/check
@@ -5,9 +5,15 @@
 
 echo -n "Diva is checking"
 diva unpack &>/o
-stack runhaskell usr/use &>/tmp/diva-check
-code=$?
-diva repack &>/o
-echo .
-exit $code
+
+if ! stack runhaskell usr/use-filer &>/tmp/diva-check
+then code=120; diva repack &>/o; echo ': filer error!'; exit $code
+fi
+
+cp var/original.md /tmp
+if ! stack runhaskell usr/use-markdown &>/tmp/diva-check
+then code=121; diva repack &>/o; echo ': markdown error!'; exit $code
+fi
+
+diva repack &>/o; echo .
 
diff --git a/.diva/cmd/test b/.diva/cmd/test
--- a/.diva/cmd/test
+++ b/.diva/cmd/test
@@ -3,10 +3,20 @@
 # $ diva test
 ##
 
-set -e
 echo -n "Diva is testing"
+cp var/original.md /tmp
 diva unpack &>/o
-stack test  &>/tmp/diva-test
-diva repack &>/o
-echo .
+
+if stack test  &>/tmp/diva-test
+then diva repack &>/o
+else code=$? diva repack &>/o; echo '!'; exit $code
+fi
+
+if test "$(cat /tmp/original.md)" == "$(cat /tmp/actual.md)"
+then echo .
+else
+    echo '!'
+    echo "error: in /tmp, actual.md != original.md" >/tmp/diva-test
+    exit 122
+fi
 
